
//input ports
add mapped point clk clk -type PI PI
add mapped point rst rst -type PI PI
add mapped point inp1[63] inp1[63] -type PI PI
add mapped point inp1[62] inp1[62] -type PI PI
add mapped point inp1[61] inp1[61] -type PI PI
add mapped point inp1[60] inp1[60] -type PI PI
add mapped point inp1[59] inp1[59] -type PI PI
add mapped point inp1[58] inp1[58] -type PI PI
add mapped point inp1[57] inp1[57] -type PI PI
add mapped point inp1[56] inp1[56] -type PI PI
add mapped point inp1[55] inp1[55] -type PI PI
add mapped point inp1[54] inp1[54] -type PI PI
add mapped point inp1[53] inp1[53] -type PI PI
add mapped point inp1[52] inp1[52] -type PI PI
add mapped point inp1[51] inp1[51] -type PI PI
add mapped point inp1[50] inp1[50] -type PI PI
add mapped point inp1[49] inp1[49] -type PI PI
add mapped point inp1[48] inp1[48] -type PI PI
add mapped point inp1[47] inp1[47] -type PI PI
add mapped point inp1[46] inp1[46] -type PI PI
add mapped point inp1[45] inp1[45] -type PI PI
add mapped point inp1[44] inp1[44] -type PI PI
add mapped point inp1[43] inp1[43] -type PI PI
add mapped point inp1[42] inp1[42] -type PI PI
add mapped point inp1[41] inp1[41] -type PI PI
add mapped point inp1[40] inp1[40] -type PI PI
add mapped point inp1[39] inp1[39] -type PI PI
add mapped point inp1[38] inp1[38] -type PI PI
add mapped point inp1[37] inp1[37] -type PI PI
add mapped point inp1[36] inp1[36] -type PI PI
add mapped point inp1[35] inp1[35] -type PI PI
add mapped point inp1[34] inp1[34] -type PI PI
add mapped point inp1[33] inp1[33] -type PI PI
add mapped point inp1[32] inp1[32] -type PI PI
add mapped point inp1[31] inp1[31] -type PI PI
add mapped point inp1[30] inp1[30] -type PI PI
add mapped point inp1[29] inp1[29] -type PI PI
add mapped point inp1[28] inp1[28] -type PI PI
add mapped point inp1[27] inp1[27] -type PI PI
add mapped point inp1[26] inp1[26] -type PI PI
add mapped point inp1[25] inp1[25] -type PI PI
add mapped point inp1[24] inp1[24] -type PI PI
add mapped point inp1[23] inp1[23] -type PI PI
add mapped point inp1[22] inp1[22] -type PI PI
add mapped point inp1[21] inp1[21] -type PI PI
add mapped point inp1[20] inp1[20] -type PI PI
add mapped point inp1[19] inp1[19] -type PI PI
add mapped point inp1[18] inp1[18] -type PI PI
add mapped point inp1[17] inp1[17] -type PI PI
add mapped point inp1[16] inp1[16] -type PI PI
add mapped point inp1[15] inp1[15] -type PI PI
add mapped point inp1[14] inp1[14] -type PI PI
add mapped point inp1[13] inp1[13] -type PI PI
add mapped point inp1[12] inp1[12] -type PI PI
add mapped point inp1[11] inp1[11] -type PI PI
add mapped point inp1[10] inp1[10] -type PI PI
add mapped point inp1[9] inp1[9] -type PI PI
add mapped point inp1[8] inp1[8] -type PI PI
add mapped point inp1[7] inp1[7] -type PI PI
add mapped point inp1[6] inp1[6] -type PI PI
add mapped point inp1[5] inp1[5] -type PI PI
add mapped point inp1[4] inp1[4] -type PI PI
add mapped point inp1[3] inp1[3] -type PI PI
add mapped point inp1[2] inp1[2] -type PI PI
add mapped point inp1[1] inp1[1] -type PI PI
add mapped point inp1[0] inp1[0] -type PI PI
add mapped point inp2[63] inp2[63] -type PI PI
add mapped point inp2[62] inp2[62] -type PI PI
add mapped point inp2[61] inp2[61] -type PI PI
add mapped point inp2[60] inp2[60] -type PI PI
add mapped point inp2[59] inp2[59] -type PI PI
add mapped point inp2[58] inp2[58] -type PI PI
add mapped point inp2[57] inp2[57] -type PI PI
add mapped point inp2[56] inp2[56] -type PI PI
add mapped point inp2[55] inp2[55] -type PI PI
add mapped point inp2[54] inp2[54] -type PI PI
add mapped point inp2[53] inp2[53] -type PI PI
add mapped point inp2[52] inp2[52] -type PI PI
add mapped point inp2[51] inp2[51] -type PI PI
add mapped point inp2[50] inp2[50] -type PI PI
add mapped point inp2[49] inp2[49] -type PI PI
add mapped point inp2[48] inp2[48] -type PI PI
add mapped point inp2[47] inp2[47] -type PI PI
add mapped point inp2[46] inp2[46] -type PI PI
add mapped point inp2[45] inp2[45] -type PI PI
add mapped point inp2[44] inp2[44] -type PI PI
add mapped point inp2[43] inp2[43] -type PI PI
add mapped point inp2[42] inp2[42] -type PI PI
add mapped point inp2[41] inp2[41] -type PI PI
add mapped point inp2[40] inp2[40] -type PI PI
add mapped point inp2[39] inp2[39] -type PI PI
add mapped point inp2[38] inp2[38] -type PI PI
add mapped point inp2[37] inp2[37] -type PI PI
add mapped point inp2[36] inp2[36] -type PI PI
add mapped point inp2[35] inp2[35] -type PI PI
add mapped point inp2[34] inp2[34] -type PI PI
add mapped point inp2[33] inp2[33] -type PI PI
add mapped point inp2[32] inp2[32] -type PI PI
add mapped point inp2[31] inp2[31] -type PI PI
add mapped point inp2[30] inp2[30] -type PI PI
add mapped point inp2[29] inp2[29] -type PI PI
add mapped point inp2[28] inp2[28] -type PI PI
add mapped point inp2[27] inp2[27] -type PI PI
add mapped point inp2[26] inp2[26] -type PI PI
add mapped point inp2[25] inp2[25] -type PI PI
add mapped point inp2[24] inp2[24] -type PI PI
add mapped point inp2[23] inp2[23] -type PI PI
add mapped point inp2[22] inp2[22] -type PI PI
add mapped point inp2[21] inp2[21] -type PI PI
add mapped point inp2[20] inp2[20] -type PI PI
add mapped point inp2[19] inp2[19] -type PI PI
add mapped point inp2[18] inp2[18] -type PI PI
add mapped point inp2[17] inp2[17] -type PI PI
add mapped point inp2[16] inp2[16] -type PI PI
add mapped point inp2[15] inp2[15] -type PI PI
add mapped point inp2[14] inp2[14] -type PI PI
add mapped point inp2[13] inp2[13] -type PI PI
add mapped point inp2[12] inp2[12] -type PI PI
add mapped point inp2[11] inp2[11] -type PI PI
add mapped point inp2[10] inp2[10] -type PI PI
add mapped point inp2[9] inp2[9] -type PI PI
add mapped point inp2[8] inp2[8] -type PI PI
add mapped point inp2[7] inp2[7] -type PI PI
add mapped point inp2[6] inp2[6] -type PI PI
add mapped point inp2[5] inp2[5] -type PI PI
add mapped point inp2[4] inp2[4] -type PI PI
add mapped point inp2[3] inp2[3] -type PI PI
add mapped point inp2[2] inp2[2] -type PI PI
add mapped point inp2[1] inp2[1] -type PI PI
add mapped point inp2[0] inp2[0] -type PI PI

//output ports
add mapped point sum[63] sum[63] -type PO PO
add mapped point sum[62] sum[62] -type PO PO
add mapped point sum[61] sum[61] -type PO PO
add mapped point sum[60] sum[60] -type PO PO
add mapped point sum[59] sum[59] -type PO PO
add mapped point sum[58] sum[58] -type PO PO
add mapped point sum[57] sum[57] -type PO PO
add mapped point sum[56] sum[56] -type PO PO
add mapped point sum[55] sum[55] -type PO PO
add mapped point sum[54] sum[54] -type PO PO
add mapped point sum[53] sum[53] -type PO PO
add mapped point sum[52] sum[52] -type PO PO
add mapped point sum[51] sum[51] -type PO PO
add mapped point sum[50] sum[50] -type PO PO
add mapped point sum[49] sum[49] -type PO PO
add mapped point sum[48] sum[48] -type PO PO
add mapped point sum[47] sum[47] -type PO PO
add mapped point sum[46] sum[46] -type PO PO
add mapped point sum[45] sum[45] -type PO PO
add mapped point sum[44] sum[44] -type PO PO
add mapped point sum[43] sum[43] -type PO PO
add mapped point sum[42] sum[42] -type PO PO
add mapped point sum[41] sum[41] -type PO PO
add mapped point sum[40] sum[40] -type PO PO
add mapped point sum[39] sum[39] -type PO PO
add mapped point sum[38] sum[38] -type PO PO
add mapped point sum[37] sum[37] -type PO PO
add mapped point sum[36] sum[36] -type PO PO
add mapped point sum[35] sum[35] -type PO PO
add mapped point sum[34] sum[34] -type PO PO
add mapped point sum[33] sum[33] -type PO PO
add mapped point sum[32] sum[32] -type PO PO
add mapped point sum[31] sum[31] -type PO PO
add mapped point sum[30] sum[30] -type PO PO
add mapped point sum[29] sum[29] -type PO PO
add mapped point sum[28] sum[28] -type PO PO
add mapped point sum[27] sum[27] -type PO PO
add mapped point sum[26] sum[26] -type PO PO
add mapped point sum[25] sum[25] -type PO PO
add mapped point sum[24] sum[24] -type PO PO
add mapped point sum[23] sum[23] -type PO PO
add mapped point sum[22] sum[22] -type PO PO
add mapped point sum[21] sum[21] -type PO PO
add mapped point sum[20] sum[20] -type PO PO
add mapped point sum[19] sum[19] -type PO PO
add mapped point sum[18] sum[18] -type PO PO
add mapped point sum[17] sum[17] -type PO PO
add mapped point sum[16] sum[16] -type PO PO
add mapped point sum[15] sum[15] -type PO PO
add mapped point sum[14] sum[14] -type PO PO
add mapped point sum[13] sum[13] -type PO PO
add mapped point sum[12] sum[12] -type PO PO
add mapped point sum[11] sum[11] -type PO PO
add mapped point sum[10] sum[10] -type PO PO
add mapped point sum[9] sum[9] -type PO PO
add mapped point sum[8] sum[8] -type PO PO
add mapped point sum[7] sum[7] -type PO PO
add mapped point sum[6] sum[6] -type PO PO
add mapped point sum[5] sum[5] -type PO PO
add mapped point sum[4] sum[4] -type PO PO
add mapped point sum[3] sum[3] -type PO PO
add mapped point sum[2] sum[2] -type PO PO
add mapped point sum[1] sum[1] -type PO PO
add mapped point sum[0] sum[0] -type PO PO
add mapped point cout cout -type PO PO

//inout ports




//Sequential Pins
add mapped point A[0]/q A_reg_0_/Q -type DLAT DLAT
add mapped point A[1]/q A_reg_1_/Q -type DLAT DLAT
add mapped point A[2]/q A_reg_2_/Q -type DLAT DLAT
add mapped point A[3]/q A_reg_3_/Q -type DLAT DLAT
add mapped point A[4]/q A_reg_4_/Q -type DLAT DLAT
add mapped point A[5]/q A_reg_5_/Q -type DLAT DLAT
add mapped point A[6]/q A_reg_6_/Q -type DLAT DLAT
add mapped point A[7]/q A_reg_7_/Q -type DLAT DLAT
add mapped point A[8]/q A_reg_8_/Q -type DLAT DLAT
add mapped point A[9]/q A_reg_9_/Q -type DLAT DLAT
add mapped point A[10]/q A_reg_10_/Q -type DLAT DLAT
add mapped point A[11]/q A_reg_11_/Q -type DLAT DLAT
add mapped point A[12]/q A_reg_12_/Q -type DLAT DLAT
add mapped point A[13]/q A_reg_13_/Q -type DLAT DLAT
add mapped point A[14]/q A_reg_14_/Q -type DLAT DLAT
add mapped point A[15]/q A_reg_15_/Q -type DLAT DLAT
add mapped point A[16]/q A_reg_16_/Q -type DLAT DLAT
add mapped point A[17]/q A_reg_17_/Q -type DLAT DLAT
add mapped point A[18]/q A_reg_18_/Q -type DLAT DLAT
add mapped point A[19]/q A_reg_19_/Q -type DLAT DLAT
add mapped point A[20]/q A_reg_20_/Q -type DLAT DLAT
add mapped point A[21]/q A_reg_21_/Q -type DLAT DLAT
add mapped point A[22]/q A_reg_22_/Q -type DLAT DLAT
add mapped point A[23]/q A_reg_23_/Q -type DLAT DLAT
add mapped point A[24]/q A_reg_24_/Q -type DLAT DLAT
add mapped point A[25]/q A_reg_25_/Q -type DLAT DLAT
add mapped point A[26]/q A_reg_26_/Q -type DLAT DLAT
add mapped point A[27]/q A_reg_27_/Q -type DLAT DLAT
add mapped point A[28]/q A_reg_28_/Q -type DLAT DLAT
add mapped point A[29]/q A_reg_29_/Q -type DLAT DLAT
add mapped point A[30]/q A_reg_30_/Q -type DLAT DLAT
add mapped point A[31]/q A_reg_31_/Q -type DLAT DLAT
add mapped point B[0]/q B_reg_0_/Q -type DLAT DLAT
add mapped point B[1]/q B_reg_1_/Q -type DLAT DLAT
add mapped point B[2]/q B_reg_2_/Q -type DLAT DLAT
add mapped point B[3]/q B_reg_3_/Q -type DLAT DLAT
add mapped point B[4]/q B_reg_4_/Q -type DLAT DLAT
add mapped point B[5]/q B_reg_5_/Q -type DLAT DLAT
add mapped point B[6]/q B_reg_6_/Q -type DLAT DLAT
add mapped point B[7]/q B_reg_7_/Q -type DLAT DLAT
add mapped point B[8]/q B_reg_8_/Q -type DLAT DLAT
add mapped point B[9]/q B_reg_9_/Q -type DLAT DLAT
add mapped point B[10]/q B_reg_10_/Q -type DLAT DLAT
add mapped point B[11]/q B_reg_11_/Q -type DLAT DLAT
add mapped point B[12]/q B_reg_12_/Q -type DLAT DLAT
add mapped point B[13]/q B_reg_13_/Q -type DLAT DLAT
add mapped point B[14]/q B_reg_14_/Q -type DLAT DLAT
add mapped point B[15]/q B_reg_15_/Q -type DLAT DLAT
add mapped point B[16]/q B_reg_16_/Q -type DLAT DLAT
add mapped point B[17]/q B_reg_17_/Q -type DLAT DLAT
add mapped point B[18]/q B_reg_18_/Q -type DLAT DLAT
add mapped point B[19]/q B_reg_19_/Q -type DLAT DLAT
add mapped point B[20]/q B_reg_20_/Q -type DLAT DLAT
add mapped point B[21]/q B_reg_21_/Q -type DLAT DLAT
add mapped point B[22]/q B_reg_22_/Q -type DLAT DLAT
add mapped point B[23]/q B_reg_23_/Q -type DLAT DLAT
add mapped point B[24]/q B_reg_24_/Q -type DLAT DLAT
add mapped point B[25]/q B_reg_25_/Q -type DLAT DLAT
add mapped point B[26]/q B_reg_26_/Q -type DLAT DLAT
add mapped point B[27]/q B_reg_27_/Q -type DLAT DLAT
add mapped point B[28]/q B_reg_28_/Q -type DLAT DLAT
add mapped point B[29]/q B_reg_29_/Q -type DLAT DLAT
add mapped point B[30]/q B_reg_30_/Q -type DLAT DLAT
add mapped point B[31]/q B_reg_31_/Q -type DLAT DLAT
add mapped point NS[0]/q NS_reg_0_/Q -type DLAT DLAT
add mapped point NS[1]/q NS_reg_1_/Q -type DLAT DLAT
add mapped point PS[0]/q PS_reg_0_/Q -type DFF DFF
add mapped point PS[1]/q PS_reg_1_/Q -type DFF DFF
add mapped point cout/q cout_reg/Q -type DLAT DLAT
add mapped point high_output[0]/q high_output_reg_0_/Q -type DLAT DLAT
add mapped point high_output[1]/q high_output_reg_1_/Q -type DLAT DLAT
add mapped point high_output[2]/q high_output_reg_2_/Q -type DLAT DLAT
add mapped point high_output[3]/q high_output_reg_3_/Q -type DLAT DLAT
add mapped point high_output[4]/q high_output_reg_4_/Q -type DLAT DLAT
add mapped point high_output[5]/q high_output_reg_5_/Q -type DLAT DLAT
add mapped point high_output[6]/q high_output_reg_6_/Q -type DLAT DLAT
add mapped point high_output[7]/q high_output_reg_7_/Q -type DLAT DLAT
add mapped point high_output[8]/q high_output_reg_8_/Q -type DLAT DLAT
add mapped point high_output[9]/q high_output_reg_9_/Q -type DLAT DLAT
add mapped point high_output[10]/q high_output_reg_10_/Q -type DLAT DLAT
add mapped point high_output[11]/q high_output_reg_11_/Q -type DLAT DLAT
add mapped point high_output[12]/q high_output_reg_12_/Q -type DLAT DLAT
add mapped point high_output[13]/q high_output_reg_13_/Q -type DLAT DLAT
add mapped point high_output[14]/q high_output_reg_14_/Q -type DLAT DLAT
add mapped point high_output[15]/q high_output_reg_15_/Q -type DLAT DLAT
add mapped point high_output[16]/q high_output_reg_16_/Q -type DLAT DLAT
add mapped point high_output[17]/q high_output_reg_17_/Q -type DLAT DLAT
add mapped point high_output[18]/q high_output_reg_18_/Q -type DLAT DLAT
add mapped point high_output[19]/q high_output_reg_19_/Q -type DLAT DLAT
add mapped point high_output[20]/q high_output_reg_20_/Q -type DLAT DLAT
add mapped point high_output[21]/q high_output_reg_21_/Q -type DLAT DLAT
add mapped point high_output[22]/q high_output_reg_22_/Q -type DLAT DLAT
add mapped point high_output[23]/q high_output_reg_23_/Q -type DLAT DLAT
add mapped point high_output[24]/q high_output_reg_24_/Q -type DLAT DLAT
add mapped point high_output[25]/q high_output_reg_25_/Q -type DLAT DLAT
add mapped point high_output[26]/q high_output_reg_26_/Q -type DLAT DLAT
add mapped point high_output[27]/q high_output_reg_27_/Q -type DLAT DLAT
add mapped point high_output[28]/q high_output_reg_28_/Q -type DLAT DLAT
add mapped point high_output[29]/q high_output_reg_29_/Q -type DLAT DLAT
add mapped point high_output[30]/q high_output_reg_30_/Q -type DLAT DLAT
add mapped point high_output[31]/q high_output_reg_31_/Q -type DLAT DLAT
add mapped point low_output[0]/q low_output_reg_0_/Q -type DLAT DLAT
add mapped point low_output[1]/q low_output_reg_1_/Q -type DLAT DLAT
add mapped point low_output[2]/q low_output_reg_2_/Q -type DLAT DLAT
add mapped point low_output[3]/q low_output_reg_3_/Q -type DLAT DLAT
add mapped point low_output[4]/q low_output_reg_4_/Q -type DLAT DLAT
add mapped point low_output[5]/q low_output_reg_5_/Q -type DLAT DLAT
add mapped point low_output[6]/q low_output_reg_6_/Q -type DLAT DLAT
add mapped point low_output[7]/q low_output_reg_7_/Q -type DLAT DLAT
add mapped point low_output[8]/q low_output_reg_8_/Q -type DLAT DLAT
add mapped point low_output[9]/q low_output_reg_9_/Q -type DLAT DLAT
add mapped point low_output[10]/q low_output_reg_10_/Q -type DLAT DLAT
add mapped point low_output[11]/q low_output_reg_11_/Q -type DLAT DLAT
add mapped point low_output[12]/q low_output_reg_12_/Q -type DLAT DLAT
add mapped point low_output[13]/q low_output_reg_13_/Q -type DLAT DLAT
add mapped point low_output[14]/q low_output_reg_14_/Q -type DLAT DLAT
add mapped point low_output[15]/q low_output_reg_15_/Q -type DLAT DLAT
add mapped point low_output[16]/q low_output_reg_16_/Q -type DLAT DLAT
add mapped point low_output[17]/q low_output_reg_17_/Q -type DLAT DLAT
add mapped point low_output[18]/q low_output_reg_18_/Q -type DLAT DLAT
add mapped point low_output[19]/q low_output_reg_19_/Q -type DLAT DLAT
add mapped point low_output[20]/q low_output_reg_20_/Q -type DLAT DLAT
add mapped point low_output[21]/q low_output_reg_21_/Q -type DLAT DLAT
add mapped point low_output[22]/q low_output_reg_22_/Q -type DLAT DLAT
add mapped point low_output[23]/q low_output_reg_23_/Q -type DLAT DLAT
add mapped point low_output[24]/q low_output_reg_24_/Q -type DLAT DLAT
add mapped point low_output[25]/q low_output_reg_25_/Q -type DLAT DLAT
add mapped point low_output[26]/q low_output_reg_26_/Q -type DLAT DLAT
add mapped point low_output[27]/q low_output_reg_27_/Q -type DLAT DLAT
add mapped point low_output[28]/q low_output_reg_28_/Q -type DLAT DLAT
add mapped point low_output[29]/q low_output_reg_29_/Q -type DLAT DLAT
add mapped point low_output[30]/q low_output_reg_30_/Q -type DLAT DLAT
add mapped point low_output[31]/q low_output_reg_31_/Q -type DLAT DLAT
add mapped point sum[0]/q sum_reg_0_/Q -type DLAT DLAT
add mapped point sum[1]/q sum_reg_1_/Q -type DLAT DLAT
add mapped point sum[2]/q sum_reg_2_/Q -type DLAT DLAT
add mapped point sum[3]/q sum_reg_3_/Q -type DLAT DLAT
add mapped point sum[4]/q sum_reg_4_/Q -type DLAT DLAT
add mapped point sum[5]/q sum_reg_5_/Q -type DLAT DLAT
add mapped point sum[6]/q sum_reg_6_/Q -type DLAT DLAT
add mapped point sum[7]/q sum_reg_7_/Q -type DLAT DLAT
add mapped point sum[8]/q sum_reg_8_/Q -type DLAT DLAT
add mapped point sum[9]/q sum_reg_9_/Q -type DLAT DLAT
add mapped point sum[10]/q sum_reg_10_/Q -type DLAT DLAT
add mapped point sum[11]/q sum_reg_11_/Q -type DLAT DLAT
add mapped point sum[12]/q sum_reg_12_/Q -type DLAT DLAT
add mapped point sum[13]/q sum_reg_13_/Q -type DLAT DLAT
add mapped point sum[14]/q sum_reg_14_/Q -type DLAT DLAT
add mapped point sum[15]/q sum_reg_15_/Q -type DLAT DLAT
add mapped point sum[16]/q sum_reg_16_/Q -type DLAT DLAT
add mapped point sum[17]/q sum_reg_17_/Q -type DLAT DLAT
add mapped point sum[18]/q sum_reg_18_/Q -type DLAT DLAT
add mapped point sum[19]/q sum_reg_19_/Q -type DLAT DLAT
add mapped point sum[20]/q sum_reg_20_/Q -type DLAT DLAT
add mapped point sum[21]/q sum_reg_21_/Q -type DLAT DLAT
add mapped point sum[22]/q sum_reg_22_/Q -type DLAT DLAT
add mapped point sum[23]/q sum_reg_23_/Q -type DLAT DLAT
add mapped point sum[24]/q sum_reg_24_/Q -type DLAT DLAT
add mapped point sum[25]/q sum_reg_25_/Q -type DLAT DLAT
add mapped point sum[26]/q sum_reg_26_/Q -type DLAT DLAT
add mapped point sum[27]/q sum_reg_27_/Q -type DLAT DLAT
add mapped point sum[28]/q sum_reg_28_/Q -type DLAT DLAT
add mapped point sum[29]/q sum_reg_29_/Q -type DLAT DLAT
add mapped point sum[30]/q sum_reg_30_/Q -type DLAT DLAT
add mapped point sum[31]/q sum_reg_31_/Q -type DLAT DLAT
add mapped point sum[32]/q sum_reg_32_/Q -type DLAT DLAT
add mapped point sum[33]/q sum_reg_33_/Q -type DLAT DLAT
add mapped point sum[34]/q sum_reg_34_/Q -type DLAT DLAT
add mapped point sum[35]/q sum_reg_35_/Q -type DLAT DLAT
add mapped point sum[36]/q sum_reg_36_/Q -type DLAT DLAT
add mapped point sum[37]/q sum_reg_37_/Q -type DLAT DLAT
add mapped point sum[38]/q sum_reg_38_/Q -type DLAT DLAT
add mapped point sum[39]/q sum_reg_39_/Q -type DLAT DLAT
add mapped point sum[40]/q sum_reg_40_/Q -type DLAT DLAT
add mapped point sum[41]/q sum_reg_41_/Q -type DLAT DLAT
add mapped point sum[42]/q sum_reg_42_/Q -type DLAT DLAT
add mapped point sum[43]/q sum_reg_43_/Q -type DLAT DLAT
add mapped point sum[44]/q sum_reg_44_/Q -type DLAT DLAT
add mapped point sum[45]/q sum_reg_45_/Q -type DLAT DLAT
add mapped point sum[46]/q sum_reg_46_/Q -type DLAT DLAT
add mapped point sum[47]/q sum_reg_47_/Q -type DLAT DLAT
add mapped point sum[48]/q sum_reg_48_/Q -type DLAT DLAT
add mapped point sum[49]/q sum_reg_49_/Q -type DLAT DLAT
add mapped point sum[50]/q sum_reg_50_/Q -type DLAT DLAT
add mapped point sum[51]/q sum_reg_51_/Q -type DLAT DLAT
add mapped point sum[52]/q sum_reg_52_/Q -type DLAT DLAT
add mapped point sum[53]/q sum_reg_53_/Q -type DLAT DLAT
add mapped point sum[54]/q sum_reg_54_/Q -type DLAT DLAT
add mapped point sum[55]/q sum_reg_55_/Q -type DLAT DLAT
add mapped point sum[56]/q sum_reg_56_/Q -type DLAT DLAT
add mapped point sum[57]/q sum_reg_57_/Q -type DLAT DLAT
add mapped point sum[58]/q sum_reg_58_/Q -type DLAT DLAT
add mapped point sum[59]/q sum_reg_59_/Q -type DLAT DLAT
add mapped point sum[60]/q sum_reg_60_/Q -type DLAT DLAT
add mapped point sum[61]/q sum_reg_61_/Q -type DLAT DLAT
add mapped point sum[62]/q sum_reg_62_/Q -type DLAT DLAT
add mapped point sum[63]/q sum_reg_63_/Q -type DLAT DLAT
add mapped point temp_c/q temp_c_reg/Q -type DLAT DLAT
add mapped point temp_cin/q temp_cin_reg/Q -type DLAT DLAT



//Black Boxes



//Empty Modules as Blackboxes
